# Generated by Django 5.1.7 on 2025-04-13 01:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SepaCreditTransfer',
            fields=[
                ('payment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('auth_id', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(max_length=10)),
                ('purpose_code', models.CharField(max_length=4)),
                ('requested_execution_date', models.DateField()),
                ('debtor_name', models.CharField(max_length=140)),
                ('debtor_iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$')])),
                ('debtor_currency', models.CharField(max_length=3)),
                ('creditor_name', models.CharField(max_length=70)),
                ('creditor_iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$')])),
                ('creditor_currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_to_end_id', models.CharField(max_length=35)),
                ('instruction_id', models.CharField(max_length=35)),
                ('remittance_structured', models.CharField(blank=True, max_length=140, null=True)),
                ('remittance_unstructured', models.CharField(blank=True, max_length=140, null=True)),
                ('debtor_address_country', models.CharField(max_length=2)),
                ('debtor_address_street', models.CharField(max_length=70)),
                ('debtor_address_zip', models.CharField(max_length=70)),
                ('creditor_address_country', models.CharField(max_length=2)),
                ('creditor_address_street', models.CharField(max_length=70)),
                ('creditor_address_zip', models.CharField(max_length=70)),
                ('creditor_agent_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transferencia SEPA',
                'verbose_name_plural': 'Transferencias SEPA',
            },
        ),
        migrations.CreateModel(
            name='SepaCreditTransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(max_length=10)),
                ('purpose_code', models.CharField(max_length=4)),
                ('requested_execution_date', models.DateField()),
                ('debtor_name', models.CharField(max_length=140)),
                ('debtor_iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$')])),
                ('debtor_currency', models.CharField(max_length=3)),
                ('creditor_name', models.CharField(max_length=70)),
                ('creditor_iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$')])),
                ('creditor_currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_to_end_id', models.CharField(max_length=35)),
                ('instruction_id', models.CharField(max_length=35)),
                ('remittance_structured', models.CharField(blank=True, max_length=140, null=True)),
                ('remittance_unstructured', models.CharField(blank=True, max_length=140, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sepa_payment.sepacredittransfer')),
            ],
            options={
                'verbose_name': 'Detalles de Transferencia SEPA',
                'verbose_name_plural': 'Detalles de Transferencias SEPA',
            },
        ),
        migrations.CreateModel(
            name='SepaCreditTransferError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.IntegerField()),
                ('error_message', models.TextField()),
                ('message_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='sepa_payment.sepacredittransfer')),
            ],
            options={
                'verbose_name': 'Error de Transferencia SEPA',
                'verbose_name_plural': 'Errores de Transferencias SEPA',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SepaCreditTransferStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RJCT', 'Rechazada'), ('RCVD', 'Recibida'), ('ACCP', 'Aceptada'), ('ACTC', 'Aceptada con cambio técnico'), ('ACSP', 'Aceptada con cambio semántico'), ('ACSC', 'Aceptada con cambio sintáctico'), ('ACWC', 'Aceptada con cambio de fecha'), ('ACWP', 'Aceptada con cambio de hora'), ('ACCC', 'Aceptada con cambio de contrato'), ('CANC', 'Cancelada'), ('PDNG', 'Pendiente')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sepa_payment.sepacredittransfer')),
            ],
            options={
                'verbose_name': 'Estado de Transferencia SEPA',
                'verbose_name_plural': 'Estados de Transferencias SEPA',
                'ordering': ['-timestamp'],
            },
        ),
    ]
